- idname: logo
  title: Logo design and visual identity
  description: Are you planning a scientific event and need a logo and a visual identity? 
  imgone: img/logo_netbio.png
  imgtwo: img/logo_netbiomed.png

- idname: illustration
  title: Scientific illustrations
  description: Do you need to illustrate your article, thesis, or protocol?
  imgone: img/oex_abelhas.png
  imgtwo: img/figure_ry_thesis.png

- idname: design
  title: Graphic design
  description: Do you need to create a poster, infographic or educational material?
  imgone: img/oex_zine.png
  imgtwo: img/oex_arroz.png